
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Stereo.Gui
{
	public partial class QuickFixesSelectionWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Stereo.Gui.QuickFixesSelectionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.Stereo.Gui.QuickFixesSelectionWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
