
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Stereo.Gui
{
	public partial class QuickFixesSelection
	{
		private global::Gtk.VBox vTaskBox;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Stereo.Gui.QuickFixesSelection
			this.Name = "MonoDevelop.Stereo.Gui.QuickFixesSelection";
			this.Title = global::Mono.Unix.Catalog.GetString ("QuickFixesSelection");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MonoDevelop.Stereo.Gui.QuickFixesSelection.Gtk.Container+ContainerChild
			this.vTaskBox = new global::Gtk.VBox ();
			this.vTaskBox.Name = "vTaskBox";
			this.vTaskBox.Spacing = 6;
			this.Add (this.vTaskBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 285;
			this.DefaultHeight = 25;
			this.Show ();
		}
	}
}
