
// This file has been generated by the GUI designer. Do not modify.
namespace Stereo
{
	public partial class QuickFixesSelectionWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Stereo.QuickFixesSelectionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Stereo.QuickFixesSelectionWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
